# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Yusuf Blogs
email: yusuf.ameri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the home to my new site! congratulations for finding me! I am new to
  this so it might make time to get this rolling. Eventually, this will be home
  to a portfolio of sorts where you can see what I am up to and what is on my
  mind. Welcome and Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whymerry.com" # the base hostname & protocol for your site
twitter_username: yusufameri
github_username:  yusufameri

# Build settings
markdown: kramdown
